grapple-solutions/grapple-cli

README.md

- Updated Readme file on instructions on how to install grpl
- Added example commands

GC-10 updated readme file

---

commands/cluster_commands/install
commands/example_commands/deploy

- Tried Installing grpl with minikube
- Tried deploying db-file and db testcases
- In cluster install, added code to check for minikube and if it doesn't exist then install it
- Check if minikube started or not, if not then start it
- In example deploy update the status checking logic for statefulset grappledb-mysql
**Testcases**
- Installing grpl using minikube
[grpl-installation.webm](https://github.com/grapple-solutions/grapple-cli/assets/163305499/81901a0b-9beb-47ee-a9ce-6e5b11fdb44b)
- Deploying db-file testcase
[testcase-db-file-deploy.webm](https://github.com/grapple-solutions/grapple-cli/assets/163305499/9510d279-08dc-4177-a7cb-84240171d079)
- Deploying db testcase
[testcase-db-file-deploy.webm](https://github.com/grapple-solutions/grapple-cli/assets/163305499/c31f7 …

Gc 12 try with minikube

---

commands/cluster
commands/cluster_commands/create
commands/cluster_commands/install
commands/cluster_commands/status
commands/example
commands/example_commands/deploy
commands/example_commands/status
commands/install
commands/upgrade
commands/version
common
grpl

- Incorporated all feedback
1.Return correct exist status
2.Prerequisite installation issues resolved
3.Resolved log files issue
4.Suppressed all stdout and store it in log file and only showed status at stdout
**Testcases**
- Video of grpl installation using minikube 
[feedback-demo.webm](https://github.com/grapple-solutions/grapple-cli/assets/163305499/dd3fb46f-24f1-4e65-8655-6649a70862c2)
- SS of grpl c i & grpl e d with status outputs
- SS of grpl installation using civo

Gc 16 first tester feedback incorporation

---

commands/example_commands/deploy
grpl

- Suppressed logs from following command
`kubectl get $i -o yaml | sed "s,infracreate-registry.cn-zhangjiakou.cr.aliyuncs.com,docker.io,g" | kubectl apply -f -; `
- sleep for 5 sec before checking statefulset status

GC-16 resolve ticket comments

---

commands/cluster_commands/install
utils/common

1. Added Support for giving params from cli
2. Added Support for giving params from json config file
3. Used same mechanism as aws-cli  for both
**Testcases**
1. Use CLI params to install grpl
2. Used Params from configfile to install grpl
a. Config File
b. Installing grpl from config file
3. Install grpl without any params

GC-6 added support for taking params from both cli and from file

---

commands/cluster_commands/install
utils/common

Added Support for giving params from cli
Added Support for giving params from json config file
Used same mechanism as aws-cli for both
reproducing:
https://github.com/grapple-solutions/grapple-cli/pull/7

Gc 6 allow input from params and from file

---

commands/cluster_commands/install
utils/common

1. Updated Params and Configfile logic to make it more centralized.
**Testcases**
1. Install using minikube
2. Install using civo

GC-6-updated-params-from-cli-of-file-logic

---

.gitignore
commands/cluster_commands/install

Fixed values-override.yaml file issue

GC-28 resolved  values-override.yaml file issue

---

commands/cluster_commands/install
utils/common
utils/constants
utils/package_installer

Fixed following problem 3,4,5 and 6 from GC-24

GC-24 fixed-installation using civo

---

VERSION
commands/cluster
commands/cluster_commands/install
commands/example
commands/upgrade
commands/version
utils/package_installer

Gc 24 fixes of testing on 20240327

---

commands/application
commands/application_commands/init
commands/cluster_commands/install
grpl
utils/checks
utils/constants
utils/help_menus
utils/package_installer

1. Created Directory Struct for grpl a i
2. Added help menu and web-doc support
3. Implemented grpl a i functionality ( cloned grapple-template repo and substituted project-name in README)
4. Added cli params support from both var from cli and file
5. Tested on Mac, Linux and using linuxbrew images
**Testcase**

Gc 15 grpl init create new grpl app based on a git template

---

commands/application_commands/init
utils/constants

- Cloned grapple-template repo into default dir
- also renamed repo with project-name

GC-15 cloned project into default dir

---

commands/resource
commands/resource_commands/deploy
grpl
template-files/db-file.yaml
utils/checks
utils/common
utils/constants
utils/help_menus
utils/package_installer

1. Implemented grpl resource deploy for db-file template
2. added help menu
3. some caveats, but creating PR for early feedback
4. command to run (with correct models value)
```
export OSTYPE=darwin
brew tap zahid-iqbal-alpha/homebrew-tap
brew install  zahid-iqbal-alpha/homebrew-tap/grapple-cli
```
```grpl c i ```
```
grpl r d --params --MODELS='customers:{"base":"Entity","name":"customers","properties":{"addressLine1":{"type":"string"},"addressLine2":{"type":"string"},"city":{"type":"string"},"contactFirstName":{"type":"string"},"contactLastName":{"type":"string"},"country":{"type":"string"},"creditLimit":{"type":"number"},"customerName":{"type":"string"},"id":{"generated":true,"defaultFn":"uuid","id":true,"required":true,"type":"string"},"generatedValue":{"generated":true …
```

GC-32 added grpl resource deploy for db-file

---

commands/resource_commands/deploy
utils/checks
utils/help_menus

Gc 46 grpl resource db file improvements

---

commands/doc
utils/common
utils/help_menus
utils/package_installer

1. Added Web Doc command for gras, grapi, gruim
2. Command to generate the doc 
`grpl doc crds`
3. Updated Command to generate the cli doc
`grpl doc cli`
**Testcase**
[Uploading Screencast from 06-05-2024 11:00:13.webm…]()

Gc 42 gras grapi gruim  documentation

---

utils/checks
utils/common

1. Resolved Comments
**Testcase**
Here I first got the error. but after fix when I re-ran the command, I didn't get any error

GC-48 improved grpl version - comments resolved

---

commands/resource_commands/deploy
template-files/db-file.yaml
utils/common
utils/constants

- resolved all three remaining comments

GC-46 resolved remaining comments

---

commands/doc
utils/common
utils/help_menus

1. Resolve PR comment on ticket
2. Now generated docs covers nested properties as well
**Testcase**
[Screencast from 13-05-2024 05:46:14.webm](https://github.com/grapple-solutions/grapple-cli/assets/163305499/7267017c-6eee-4996-9743-2508b4367861)

GC-42 generated webdoc for gras, gruim, and grapi

---

commands/resource_commands/deploy
template-files/db-file.yaml
utils/common
utils/constants
utils/package_installer

1. Update yaml construction logic, now we are using yq instead of string literals.
2. The code is now more clean, readable and easily extendable
3. Used old gruim configs, new configs weren't working
**Testcase**

GC-50 use yq to construct yaml instead of string literals

---

commands/resource_commands/deploy

- made base entity field select able

GC-52 added entity was selectable option

---

Dockerfile
commands/cluster_commands/install

added namespace for the commands to run the aws dns pod.
I did run into an issue when ns was not set to default.

namespace-for-grpl-dns-aws-route53

---

commands/resource_commands/deploy
template-files/db.yaml
utils/common
utils/help_menus

1. mysql-db
2. mysql-db-discovery
3. both internal and external
**Testcases**

Gc 45  grpl resource deploy for db (mysql case)

---

commands/cluster_commands/install

GC-57 - implement auto-installation from within the CIVO cluster (w/o… using civo cli)

GC-57 - implement auto-installation from within the CIVO cluster

---

commands/resource_commands/deploy
template-files/db.yaml
utils/checks
utils/constants

Resolved
10
11
11.1) I deployed example db but there wasn’t any cluster deployed there was well
12
13
14

Gc 55 mysql discovery internal improvements

---

commands/cluster_commands/install

- Made gum-spin work
- improved logging

GC_57 resolve gum spin issue

---

commands/resource_commands/deploy
template-files/db.yaml
utils/help_menus

GC-55 resolved remaining comments

---

commands/resource_commands/deploy
utils/help_menus

**Decsription**
1. Enabled auto discovery option
2. added question and cli param AUTO_DISCOVERY for that
**_NOTE : This PR is direct to GC-56 branch, so if GC-56 is merged into main then we'll have to merge this branch into main as well_**

GC-67 added auto-discovery option

---

commands/resource_commands/deploy
files/testdb.yaml
template-files/db.yaml
utils/help_menus

1. made fixes for GC-56
2. also resolve GC-54 fixes

GC-56 grpl discovery fixes

---

commands/cluster_commands/install
utils/common

- resolved the issue
- Testcase

Gc 57 resolved c i issue

---

template-files/db.yaml

Resolved 3rd issue in from the comments related to discoveredrepos

GC-54 resolved discoveredrepos issue in model based

---

utils/package_installer

- installing civo and kbcli using brew now
- tested 
**Testcases**

Gc 72 installation of civo and kbcli using homebrew

---

commands/resource_commands/deploy

GC-66 resolved initcontainer issue

---

commands/application_commands/init
commands/cluster_commands/install
commands/resource_commands/deploy
utils/common
utils/constants
utils/help_menus
values-templates/values-kubefirst.yaml

- added support for values override and templates support
- build in values yaml templates can be added into **values-templates** folder
**Testcase**
First usecase
`grpl cluster install --params --TARGET_PLATFORM=CIVO --CIVO_REGION=fra1 --CIVO_CLUSTER=zahid-cli --CIVO_EMAIL_ADDRESS=info@grapple-solutions.com --GRAPPLE_VERSION=0.2.4 --AUTO_CONFIRM=true --values values1.yaml`
Second usecase
`grpl cluster install --params --TARGET_PLATFORM=CIVO --CIVO_REGION=fra1 --CIVO_CLUSTER=zahid-cli --CIVO_EMAIL_ADDRESS=info@grapple-solutions.com --GRAPPLE_VERSION=0.2.4 --AUTO_CONFIRM=true --values values1.yaml values2.yaml`
Third usecase
`grpl cluster install --params --TARGET_PLATFORM=CIVO --CIVO_REGION=fra1 --CIVO_CLUSTER=zahid-cli --CIVO_EMAIL_ADDRESS=info@grapple-solutions.com …

Gc 70 allow to override values and prepared templtes

---

commands/application

1. Resolved issue
**Testcase**

GC-61 resolved name issue

---

commands/cluster_commands/install

Tested with talos cluster
Test with k3s cluster

GC-69 grpl c i resolve issue

---

utils/common

Added Support for params without --params keyword
**Testcases**

GC-58 supported params without the need for --params

---

commands/resource_commands/deploy
utils/common

Populated db-configs with actual values
**Testcase**

GC-66 added actual value of db config in init-container

---

commands/application_commands/init
commands/dev
commands/grapi
commands/gruim
grpl
utils/help_menus
utils/package_installer

- added support for grpl dev
- added support for grpl grapi
- added support for grpl gruim

Gc 82 add grpl dev command

---

commands/application_commands/init
commands/dev
commands/grapi
commands/gruim
utils/help_menus

GC-82 resolved issues

---

commands/cluster_commands/install
commands/example_commands/deploy

- updated grpl e d to use grpl r d internally

Gc 44 grpl e d improvements

---

commands/dev
commands/grapi
commands/gruim
grpl
utils/common

- resolved 15th and 16th comment
- unable to reproduce 14th
**Testcase**

Gc 82 grpl dev improvements

---

commands/cluster_commands/install
commands/example_commands/deploy
commands/resource_commands/deploy
utils/constants
utils/help_menus

added support to  specify KUBE_CONTEXT=current in all commands
**Testcase**
grpl e d
grpl r d

GC-74 added current-context support

---

commands/resource_commands/deploy
utils/common

GC-68 added grpl r d improvements

---

commands/doc
utils/help_menus
utils/package_installer

- moved Menu to the right
- added description with each command
- updated both web and cli doc
**Testcases**
CLI - Docs
CRDs Docs

GC-43 updated doc menu and move table of content to left

---

commands/cluster_commands/install
commands/example_commands/deploy
commands/resource_commands/deploy

GC-74 added current-context as default

---

commands/cluster_commands/install
utils/common

GC-added-GRAPPLE_DNS-and-Allowed-full-domain-format

---

commands/cluster_commands/install

resolved the issue
**Testcases**

GC-85 print values before approval for kubernetes in grpl c i

---

commands/cluster_commands/install

Dns Fix for kubernetes target platform
**Testcase**

GC-75 dns fix

---

commands/application_commands/init
utils/help_menus
utils/package_installer

1. Added Support for creating repo as well
2. added a new param CREATE_REPO which accepts true or false
3. Updated help menu
4. added gh installation code in package installer

GC-79-added-create-repo-feature

---

commands/cluster_commands/install
utils/help_menus

Changed the CIVO_MASTER_IP cli param name to CLUSTER_IP so that it can be used with both CIVO and Kubernetes
**Testcases**
1. Using Kubernetes as Target Platform
2. Using CIVO as Target Platform

GC-75 added ip fix

---

commands/cluster_commands/install
commands/license_commands/install

GC-91 updated GRAPPLE_LICENSE based on license value

---

commands/cluster_commands/install

GC-93 added latest

---

commands/cluster_commands/install
utils/constants
utils/help_menus

- With Github username
- With Gitlab username

Gc 95 added params for kubefirst

---

template-files/db-file.yaml
template-files/db.yaml

Removed ssl configs
After that Installed grapple and installed an example

GC-97 removed ssl config from grpl e d

---

commands/doc
utils/help_menus

Updated Cli Docs
Updated Crds Docs

GC-99-update-web-doc

---

commands/cluster_commands/install

Added logs 
Case where We successfully logged out of the register and tried again
Case where we weren't able to loggout of the register and displayed a message to user that they should logout and try again

Gc 108 helm logout

---

commands/cluster_commands/install

- Case where we are able to find email
- Case where we aren't able to find email, so we use default email

GC-115-added-default-email

---

commands/cluster_commands/install
commands/resource_commands/deploy
utils/help_menus
utils/package_installer

Gc 105 extend grpl c i to install kubeblocks

---

commands/application_commands/init
commands/cluster_commands/install
commands/example_commands/deploy
commands/license_commands/install
commands/resource_commands/deploy
grpl
utils/common

Testcases
1. Case where CIVO_CLUSTER_NAME is specified instead of CIVO_CLUSTER
2. Case where a CLI params is missing in non-tty mode
3. Case where everything was provided

Gc 114 improve params handling and error handling in non tty mode

---

commands/application_commands/init
utils/help_menus

- created a fork from grapple-templates and used that to test
https://github.com/user-attachments/assets/69fe63d7-d076-4ed2-ad61-a139d331247e

GC-127 updated grpl app init to allow overwrite of template source

---

commands/cluster_commands/install

resolved the issue, now cluster name field is populated in the secret

GC-129 resolved cluster name issue in secret

---

commands/application_commands/init
commands/cluster_commands/create
commands/cluster_commands/install
utils/common

GC-131-catch-input-without-dash-for-all-commands

---

commands/cluster_commands/install

Gc 135 issue with ip address

---

utils/help_menus

GC-139-added grapple cli installation doc in the webdoc

---

commands/example_commands/deploy

Gc 136 grpl e d should provide additional info

---

testcases/test_civo_marketplace_integration

GC-126 added civo marketplace test script

---

commands/doc
utils/help_menus

Testcase - Positive case
Testcase - Negative case

GC-141 added code to generate grpl gruim docs

---

commands/cluster_commands/install

Resolved issues with email extraction

Gc 154 issue with email extraction

---

commands/ai
commands/ai_commands/resource
commands/ai_commands/utils
commands/application
commands/application_commands/init
commands/cluster
commands/cluster_commands/create
commands/cluster_commands/install
commands/example
commands/example_commands/deploy
commands/license
commands/license_commands/install
commands/resource
commands/resource_commands/deploy
grpl
utils/checks
utils/common
utils/constants
utils/help_menus

- resolved comments on the ticket

Gc 145 grpl ai
